// Code generated from Yaak's apps/yaak-client/lib/data (MIT). DO NOT EDIT.

package desktop

var headerNameOptions = []completionPreset{
	{label: "Content-Type", info: "The original media type of the resource (prior to any content encoding applied for sending)"},
	{label: "Content-Length", info: "The size of the message body, in bytes, sent to the recipient"},
	{label: "Accept", info: "The content types, expressed as MIME types, the client is able to understand. The server uses content negotiation to select one of the proposals and informs the client of the choice with the Content-Type response header. Browsers set required values for this header based on the context of the request. For example, a browser uses different values in a request when fetching a CSS stylesheet, image, video, or a script."},
	{label: "Accept-Encoding", info: "The content encoding (usually a compression algorithm) that the client can understand. The server uses content negotiation to select one of the proposals and informs the client of that choice with the Content-Encoding response header."},
	{label: "Accept-Language", info: "The natural language and locale that the client prefers. The server uses content negotiation to select one of the proposals and informs the client of the choice with the Content-Language response header."},
	{label: "Authorization", info: "Provide credentials that authenticate a user agent with a server, allowing access to a protected resource."},
	{label: "Cache-Control"},
	{label: "Cookie"},
	{label: "Connection"},
	{label: "Content-MD5"},
	{label: "Date"},
	{label: "Expect"},
	{label: "Forwarded"},
	{label: "From"},
	{label: "Host"},
	{label: "If-Match"},
	{label: "If-Modified-Since"},
	{label: "If-None-Match"},
	{label: "If-Range"},
	{label: "If-Unmodified-Since"},
	{label: "Max-Forwards"},
	{label: "Origin"},
	{label: "Pragma"},
	{label: "Proxy-Authorization"},
	{label: "Range"},
	{label: "Referer"},
	{label: "TE"},
	{label: "User-Agent"},
	{label: "Upgrade"},
	{label: "Via"},
	{label: "Warning"},
}

var mimeTypeOptions = []completionPreset{
	{label: "application/json"},
	{label: "application/xml"},
	{label: "application/x-www-form-urlencoded"},
	{label: "multipart/form-data"},
	{label: "multipart/byteranges"},
	{label: "application/octet-stream"},
	{label: "text/plain"},
	{label: "application/javascript"},
	{label: "application/pdf"},
	{label: "text/html"},
	{label: "image/png"},
	{label: "image/jpeg"},
	{label: "image/gif"},
	{label: "image/webp"},
	{label: "text/css"},
	{label: "application/x-pkcs12"},
	{label: "application/xhtml+xml"},
	{label: "application/andrew-inset"},
	{label: "application/applixware"},
	{label: "application/atom+xml"},
	{label: "application/atomcat+xml"},
	{label: "application/atomsvc+xml"},
	{label: "application/bdoc"},
	{label: "application/cu-seeme"},
	{label: "application/davmount+xml"},
	{label: "application/docbook+xml"},
	{label: "application/dssc+xml"},
	{label: "application/ecmascript"},
	{label: "application/epub+zip"},
	{label: "application/exi"},
	{label: "application/font-tdpfr"},
	{label: "application/font-woff"},
	{label: "application/font-woff2"},
	{label: "application/geo+json"},
	{label: "application/graphql"},
	{label: "application/java-serialized-object"},
	{label: "application/json5"},
	{label: "application/jsonml+json"},
	{label: "application/ld+json"},
	{label: "application/lost+xml"},
	{label: "application/manifest+json"},
	{label: "application/mp4"},
	{label: "application/msword"},
	{label: "application/mxf"},
	{label: "application/n-triples"},
	{label: "application/n-quads"},
	{label: "application/oda"},
	{label: "application/ogg"},
	{label: "application/pgp-encrypted"},
	{label: "application/pgp-signature"},
	{label: "application/pics-rules"},
	{label: "application/pkcs10"},
	{label: "application/pkcs7-mime"},
	{label: "application/pkcs7-signature"},
	{label: "application/pkcs8"},
	{label: "application/postscript"},
	{label: "application/pskc+xml"},
	{label: "application/rdf+xml"},
	{label: "application/resource-lists+xml"},
	{label: "application/resource-lists-diff+xml"},
	{label: "application/rls-services+xml"},
	{label: "application/rsd+xml"},
	{label: "application/rss+xml"},
	{label: "application/rtf"},
	{label: "application/sdp"},
	{label: "application/shf+xml"},
	{label: "application/timestamped-data"},
	{label: "application/trig"},
	{label: "application/vnd.android.package-archive"},
	{label: "application/vnd.api+json"},
	{label: "application/vnd.apple.installer+xml"},
	{label: "application/vnd.apple.mpegurl"},
	{label: "application/vnd.apple.pkpass"},
	{label: "application/vnd.bmi"},
	{label: "application/vnd.curl.car"},
	{label: "application/vnd.curl.pcurl"},
	{label: "application/vnd.dna"},
	{label: "application/vnd.google-apps.document"},
	{label: "application/vnd.google-apps.presentation"},
	{label: "application/vnd.google-apps.spreadsheet"},
	{label: "application/vnd.hal+xml"},
	{label: "application/vnd.handheld-entertainment+xml"},
	{label: "application/vnd.macports.portpkg"},
	{label: "application/vnd.unity"},
	{label: "application/vnd.zul"},
	{label: "application/widget"},
	{label: "application/wsdl+xml"},
	{label: "application/x-7z-compressed"},
	{label: "application/x-ace-compressed"},
	{label: "application/x-bittorrent"},
	{label: "application/x-bzip"},
	{label: "application/x-bzip2"},
	{label: "application/x-cfs-compressed"},
	{label: "application/x-chrome-extension"},
	{label: "application/x-cocoa"},
	{label: "application/x-envoy"},
	{label: "application/x-eva"},
	{label: "font/opentype"},
	{label: "application/x-gca-compressed"},
	{label: "application/x-gtar"},
	{label: "application/x-hdf"},
	{label: "application/x-httpd-php"},
	{label: "application/x-install-instructions"},
	{label: "application/x-latex"},
	{label: "application/x-lua-bytecode"},
	{label: "application/x-lzh-compressed"},
	{label: "application/x-ms-application"},
	{label: "application/x-ms-shortcut"},
	{label: "application/x-ndjson"},
	{label: "application/x-perl"},
	{label: "application/x-pkcs7-certificates"},
	{label: "application/x-pkcs7-certreqresp"},
	{label: "application/x-rar-compressed"},
	{label: "application/x-sh"},
	{label: "application/x-sql"},
	{label: "application/x-subrip"},
	{label: "application/x-t3vm-image"},
	{label: "application/x-tads"},
	{label: "application/x-tar"},
	{label: "application/x-tcl"},
	{label: "application/x-tex"},
	{label: "application/x-x509-ca-cert"},
	{label: "application/xop+xml"},
	{label: "application/xslt+xml"},
	{label: "application/zip"},
	{label: "audio/3gpp"},
	{label: "audio/adpcm"},
	{label: "audio/basic"},
	{label: "audio/midi"},
	{label: "audio/mpeg"},
	{label: "audio/mp4"},
	{label: "audio/ogg"},
	{label: "audio/silk"},
	{label: "audio/wave"},
	{label: "audio/webm"},
	{label: "audio/x-aac"},
	{label: "audio/x-aiff"},
	{label: "audio/x-caf"},
	{label: "audio/x-flac"},
	{label: "audio/xm"},
	{label: "image/bmp"},
	{label: "image/cgm"},
	{label: "image/sgi"},
	{label: "image/svg+xml"},
	{label: "image/tiff"},
	{label: "image/x-3ds"},
	{label: "image/x-freehand"},
	{label: "image/x-icon"},
	{label: "image/x-jng"},
	{label: "image/x-mrsid-image"},
	{label: "image/x-pcx"},
	{label: "image/x-pict"},
	{label: "image/x-rgb"},
	{label: "image/x-tga"},
	{label: "message/rfc822"},
	{label: "text/cache-manifest"},
	{label: "text/calendar"},
	{label: "text/coffeescript"},
	{label: "text/csv"},
	{label: "text/hjson"},
	{label: "text/jade"},
	{label: "text/jsx"},
	{label: "text/less"},
	{label: "text/mathml"},
	{label: "text/n3"},
	{label: "text/richtext"},
	{label: "text/sgml"},
	{label: "text/slim"},
	{label: "text/stylus"},
	{label: "text/tab-separated-values"},
	{label: "text/turtle"},
	{label: "text/uri-list"},
	{label: "text/vcard"},
	{label: "text/vnd.curl"},
	{label: "text/vnd.fly"},
	{label: "text/vtt"},
	{label: "text/x-asm"},
	{label: "text/x-c"},
	{label: "text/x-component"},
	{label: "text/x-fortran"},
	{label: "text/x-handlebars-template"},
	{label: "text/x-java-source"},
	{label: "text/x-lua"},
	{label: "text/x-markdown"},
	{label: "text/x-nfo"},
	{label: "text/x-opml"},
	{label: "text/x-pascal"},
	{label: "text/x-processing"},
	{label: "text/x-sass"},
	{label: "text/x-scss"},
	{label: "text/x-vcalendar"},
	{label: "text/xml"},
	{label: "text/yaml"},
	{label: "video/3gpp"},
	{label: "video/3gpp2"},
	{label: "video/h261"},
	{label: "video/h263"},
	{label: "video/h264"},
	{label: "video/jpeg"},
	{label: "video/jpm"},
	{label: "video/mj2"},
	{label: "video/mp2t"},
	{label: "video/mp4"},
	{label: "video/mpeg"},
	{label: "video/ogg"},
	{label: "video/quicktime"},
	{label: "video/webm"},
	{label: "video/x-f4v"},
	{label: "video/x-fli"},
	{label: "video/x-flv"},
	{label: "video/x-m4v"},
}

var charsetOptions = []completionPreset{
	{label: "utf-8"},
	{label: "us-ascii"},
	{label: "950"},
	{label: "ASMO-708"},
	{label: "CP1026"},
	{label: "CP870"},
	{label: "DOS-720"},
	{label: "DOS-862"},
	{label: "EUC-CN"},
	{label: "IBM437"},
	{label: "Johab"},
	{label: "Windows-1252"},
	{label: "X-EBCDIC-Spain"},
	{label: "big5"},
	{label: "cp866"},
	{label: "csISO2022JP"},
	{label: "ebcdic-cp-us"},
	{label: "euc-kr"},
	{label: "gb2312"},
	{label: "hz-gb-2312"},
	{label: "ibm737"},
	{label: "ibm775"},
	{label: "ibm850"},
	{label: "ibm852"},
	{label: "ibm857"},
	{label: "ibm861"},
	{label: "ibm869"},
	{label: "iso-2022-jp"},
	{label: "iso-2022-jp"},
	{label: "iso-2022-kr"},
	{label: "iso-8859-1"},
	{label: "iso-8859-15"},
	{label: "iso-8859-2"},
	{label: "iso-8859-3"},
	{label: "iso-8859-4"},
	{label: "iso-8859-5"},
	{label: "iso-8859-6"},
	{label: "iso-8859-7"},
	{label: "iso-8859-8"},
	{label: "iso-8859-8-i"},
	{label: "iso-8859-9"},
	{label: "koi8-r"},
	{label: "koi8-u"},
	{label: "ks_c_5601-1987"},
	{label: "macintosh"},
	{label: "shift_jis"},
	{label: "unicode"},
	{label: "unicodeFFFE"},
	{label: "utf-7"},
	{label: "windows-1250"},
	{label: "windows-1251"},
	{label: "windows-1253"},
	{label: "windows-1254"},
	{label: "windows-1255"},
	{label: "windows-1256"},
	{label: "windows-1257"},
	{label: "windows-1258"},
	{label: "windows-874"},
	{label: "x-Chinese-CNS"},
	{label: "x-Chinese-Eten"},
	{label: "x-EBCDIC-Arabic"},
	{label: "x-EBCDIC-CyrillicRussian"},
	{label: "x-EBCDIC-CyrillicSerbianBulgarian"},
	{label: "x-EBCDIC-DenmarkNorway"},
	{label: "x-EBCDIC-FinlandSweden"},
	{label: "x-EBCDIC-Germany"},
	{label: "x-EBCDIC-Greek"},
	{label: "x-EBCDIC-GreekModern"},
	{label: "x-EBCDIC-Hebrew"},
	{label: "x-EBCDIC-Icelandic"},
	{label: "x-EBCDIC-Italy"},
	{label: "x-EBCDIC-JapaneseAndJapaneseLatin"},
	{label: "x-EBCDIC-JapaneseAndKana"},
	{label: "x-EBCDIC-JapaneseAndUSCanada"},
	{label: "x-EBCDIC-JapaneseKatakana"},
	{label: "x-EBCDIC-KoreanAndKoreanExtended"},
	{label: "x-EBCDIC-KoreanExtended"},
	{label: "x-EBCDIC-SimplifiedChinese"},
	{label: "x-EBCDIC-Thai"},
	{label: "x-EBCDIC-TraditionalChinese"},
	{label: "x-EBCDIC-Turkish"},
	{label: "x-EBCDIC-UK"},
	{label: "x-Europa"},
	{label: "x-IA5"},
	{label: "x-IA5-German"},
	{label: "x-IA5-Norwegian"},
	{label: "x-IA5-Swedish"},
	{label: "x-ebcdic-cp-us-euro"},
	{label: "x-ebcdic-denmarknorway-euro"},
	{label: "x-ebcdic-finlandsweden-euro"},
	{label: "x-ebcdic-finlandsweden-euro"},
	{label: "x-ebcdic-france-euro"},
	{label: "x-ebcdic-germany-euro"},
	{label: "x-ebcdic-icelandic-euro"},
	{label: "x-ebcdic-international-euro"},
	{label: "x-ebcdic-italy-euro"},
	{label: "x-ebcdic-spain-euro"},
	{label: "x-ebcdic-uk-euro"},
	{label: "x-euc-jp"},
	{label: "x-iscii-as"},
	{label: "x-iscii-be"},
	{label: "x-iscii-de"},
	{label: "x-iscii-gu"},
	{label: "x-iscii-ka"},
	{label: "x-iscii-ma"},
	{label: "x-iscii-or"},
	{label: "x-iscii-pa"},
	{label: "x-iscii-ta"},
	{label: "x-iscii-te"},
	{label: "x-mac-arabic"},
	{label: "x-mac-ce"},
	{label: "x-mac-chinesesimp"},
	{label: "x-mac-cyrillic"},
	{label: "x-mac-greek"},
	{label: "x-mac-hebrew"},
	{label: "x-mac-icelandic"},
	{label: "x-mac-japanese"},
	{label: "x-mac-korean"},
	{label: "x-mac-turkish"},
}

var connectionOptions = []completionPreset{
	{label: "close"},
	{label: "keep-alive"},
}

var encodingOptions = []completionPreset{
	{label: "*"},
	{label: "gzip"},
	{label: "compress"},
	{label: "deflate"},
	{label: "br"},
	{label: "zstd"},
	{label: "identity"},
}

var acceptLanguageOptions = []completionPreset{
	{label: "*"},
	{label: "en"},
	{label: "en-US"},
	{label: "en-US,en;q=0.9"},
	{label: "en-GB,en;q=0.9"},
	{label: "de-DE,de;q=0.9,en;q=0.8"},
	{label: "fr-FR,fr;q=0.9,en;q=0.8"},
	{label: "es-ES,es;q=0.9,en;q=0.8"},
	{label: "ru-RU,ru;q=0.9,en;q=0.8"},
	{label: "uk-UA,uk;q=0.9,en;q=0.8"},
	{label: "zh-CN,zh;q=0.9,en;q=0.8"},
	{label: "ja-JP,ja;q=0.9,en;q=0.8"},
}

var cacheControlOptions = []completionPreset{
	{label: "no-cache"},
	{label: "no-store"},
	{label: "no-transform"},
	{label: "max-age=0"},
	{label: "max-age=3600"},
	{label: "max-age=86400"},
	{label: "s-maxage=3600"},
	{label: "must-revalidate"},
	{label: "proxy-revalidate"},
	{label: "stale-while-revalidate=60"},
	{label: "public"},
	{label: "private"},
	{label: "immutable"},
}

var userAgentOptions = []completionPreset{
	{label: "Chrome 151 · Windows 10/11 · x64", value: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36"},
	{label: "Edge 151 · Windows 10/11 · x64", value: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36 Edg/151.0.0.0"},
	{label: "Firefox 153 · Windows 10/11 · x64", value: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:153.0) Gecko/20100101 Firefox/153.0"},
	{label: "Chrome 151 · macOS", value: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36"},
	{label: "Safari 27 · macOS", value: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/27.0 Safari/605.1.15"},
	{label: "Chrome 151 · Linux · x64", value: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36"},
	{label: "Safari 27 · iOS 27 · iPhone", value: "Mozilla/5.0 (iPhone; CPU iPhone OS 27_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/27.0 Mobile/15E148 Safari/604.1"},
	{label: "Chrome 151 · Android 16 · Pixel 10", value: "Mozilla/5.0 (Linux; Android 16; Pixel 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Mobile Safari/537.36"},
	{label: "curl 8.21.0 · CLI", value: "curl/8.21.0"},
	{label: "Postman 7.56 · API client", value: "PostmanRuntime/7.56.1"},
	{label: "Insomnia 13.1 · API client", value: "insomnia/13.1.0"},
}
